apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: hello
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: hello
        image: wdalmut/hello
