apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello
        image: wdalmut/hello
        ports:
        - containerPort: 3000
